### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by thehairy** [NotRealArif/printly.js#3]
Even tho this package is completely useless, as you can literally install the dependencies yourself and end up using nearly the same code...

This package lacks typescript support, which you claim to have.
For typescript support you need at least the typings.

You can make a types.d.ts file for that and create your types there.

**Comment by ItzYourBread** [comment]
Ok I will do that soon

**Comment by ItzYourBread** [comment]
Fixed now you just have to do import { printly } = “printly.js”;
